---
- name: Create Transmission container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_torrent_name }}"
    image: "{{ docker_torrent_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_torrent_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_torrent_name }}"
      fluentd-async: "true"
    capabilities:
      - NET_ADMIN
    # published_ports:
    #   - "9091:9091"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    networks_cli_compatible: yes
    env:
      TZ: "{{ homelab_timezone }}"
      UMASK_SET: "022"
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
      CREATE_TUN_DEVICE: "true"
      OPENVPN_PROVIDER: "{{ docker_torrent_openvpn_provider }}"
      OPENVPN_USERNAME: "{{ docker_torrent_openvpn_username }}"
      OPENVPN_PASSWORD: "{{ docker_torrent_openvpn_password }}"
      WEBPROXY_ENABLED: "true"
      LOCAL_NETWORK: "{{ docker_torrent_local_network }}"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_RATIO_LIMIT: "0.5"
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_IDLE_SEEDING_LIMIT: "15"
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP: "128"
      #TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      #TRANSMISSION_SPEED_LIMIT_DOWN: "512"
      TRANSMISSION_ALT_SPEED_TIME_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_TIME_BEGIN: "420"
      TRANSMISSION_ALT_SPEED_TIME_END: "1380"
      TRANSMISSION_ALT_SPEED_DOWN: "128"
    labels:
      traefik.enable: "true"
      traefik.http.routers.transmission.entrypoints: "websecure"
      traefik.http.services.transmission.loadbalancer.server.port: "9091"
      traefik.http.routers.transmission.rule: "Host(`{{ docker_torrent_proxy_hostname }}`)"
      traefik.http.routers.transmission.tls: "true"
      traefik.http.routers.transmission.tls.certresolver: "le"
    volumes:
      - "{{ docker_torrent_mount_config }}:/config"
      - "{{ docker_download_mount_media }}:/data"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
    state: present

- name: Start Transmission container
  docker_container:
    name: "{{ docker_torrent_name }}"
    container_default_behavior: "no_defaults"
    state: started