---
- name: Create data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0755
    recurse: yes
  with_items:
    - "{{ docker_photoprism_mount_mariadb }}"
    - "{{ docker_photoprism_mount_photoprism }}"
    - "{{ docker_photoprism_mount_storage }}"

- name: Determine if originals directory exists
  stat:
    path: "{{ docker_photoprism_mount_originals }}"
  register: media_path

- name: Create originals directory but don't mess with existing/mounted folder
  file:
    path: "{{ docker_photoprism_mount_originals }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0775
    state: directory
    recurse: yes
  when: not media_path.stat.exists