---
- name: Create MariaDB container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_photoprism_mariadb_name }}"
    image: "{{ docker_photoprism_mariadb_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_photoprism_mariadb_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_photoprism_mariadb_name }}"
      fluentd-async: "true"
    env:
      TZ: "{{ homelab_timezone }}"
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
      MYSQL_ROOT_PASSWORD: "{{ docker_photoprism_mariadb_password }}"
      MYSQL_DATABASE: "{{ docker_photoprism_mariadb_db }}"
      MYSQL_USER: "{{ docker_photoprism_mariadb_user }}"
      MYSQL_PASSWORD: "{{ docker_photoprism_mariadb_password }}"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ docker_photoprism_mount_mariadb }}:/config"
    restart_policy: unless-stopped
    state: present

- name: Start MariaDB container
  docker_container:
    name: "{{ docker_photoprism_mariadb_name }}"
    container_default_behavior: "no_defaults"
    state: started