---
- name: Create Bazarr container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_bazarr_name }}"
    image: "{{ docker_bazarr_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_bazarr_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_bazarr_name }}"
      fluentd-async: "true"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    networks_cli_compatible: yes
    env:
        TZ: "{{ system_timezone }}"
        UMASK_SET: "022"
        PUID: "{{ docker_user_uid }}"
        PGID: "{{ docker_group_gid }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.bazarr.entrypoints: "websecure"
      traefik.http.routers.bazarr.rule: "Host(`{{ docker_bazarr_proxy_hostname }}`)"
      traefik.http.routers.bazarr.tls: "true"
      traefik.http.routers.bazarr.tls.certresolver: "le"
    volumes:
      - "{{ docker_bazarr_mount_config }}:/config"
      - "{{ docker_download_mount_media }}:/data"
    restart_policy: unless-stopped
    state: present

- name: Start Bazarr
  docker_container:
    name: "{{ docker_bazarr_name }}"
    container_default_behavior: "no_defaults"
    state: started