---
- name: Create Gluetun container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_gluetun_name }}"
    image: "{{ docker_gluetun_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_gluetun_name }}"
      fluentd-async: "true"
    capabilities:
      - NET_ADMIN
    network_mode: bridge
    published_ports:
      - "8888:8888/tcp" # HTTP proxy
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
      - "9091:9091" # Torrent
      - "51413:51413" # Torrent
      - "51413:51413/udp" # Torrent
    networks:
      - name: "{{ docker_network }}"
    networks_cli_compatible: yes
    env:
      TZ: "{{ system_timezone }}"
      VPN_SERVICE_PROVIDER: "nordvpn"
      OPENVPN_USER: "{{ docker_gluetun_username }}"
      OPENVPN_PASSWORD: "{{ docker_gluetun_password }}"
      SERVER_REGIONS: "{{ docker_gluetun_region }}"
      HTTPPROXY: "on"
    volumes:
      - "{{ docker_gluetun_mount_config }}:/gluetun"
    restart_policy: unless-stopped
    state: present

- name: Start Gluetun container
  docker_container:
    name: "{{ docker_gluetun_name }}"
    container_default_behavior: "no_defaults"
    state: started