---
- name: Create Transmission container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_torrent_name }}"
    image: "{{ docker_torrent_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_torrent_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_torrent_name }}"
      fluentd-async: "true"
    network_mode: "container:{{ docker_gluetun_name }}"
    networks:
      - name: "{{ docker_network }}"
    networks_cli_compatible: yes
    env:
      TZ: "{{ system_timezone }}"
      UMASK_SET: "022"
      PUID: "{{ docker_user_uid }}"
      PGID: "{{ docker_group_gid }}"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_RATIO_LIMIT: "0.5"
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_IDLE_SEEDING_LIMIT: "15"
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP: "128"
      TRANSMISSION_ALT_SPEED_TIME_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_TIME_BEGIN: "420"
      TRANSMISSION_ALT_SPEED_TIME_END: "1380"
      TRANSMISSION_ALT_SPEED_DOWN: "128"
    volumes:
      - "{{ docker_torrent_mount_config }}:/config"
      - "{{ docker_download_mount_media }}:/data"
    restart_policy: unless-stopped
    state: present

- name: Start Transmission container
  docker_container:
    name: "{{ docker_torrent_name }}"
    container_default_behavior: "no_defaults"
    state: started