---
- name: Create Adminer container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_adminer_name }}"
    image: "{{ docker_adminer_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_adminer_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_adminer_name }}"
      fluentd-async: "true"
    env:
      ADMINER_DEFAULT_SERVER: "{{ docker_adminer_default_server }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.adminer.entrypoints: "websecure"
      traefik.http.routers.adminer.rule: "Host(`{{ docker_adminer_proxy_hostname }}`)"
      traefik.http.routers.adminer.tls: "true"
      traefik.http.routers.adminer.tls.certresolver: "le"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    restart_policy: unless-stopped
    state: present

- name: Start Adminer container
  docker_container:
    name: "{{ docker_adminer_name }}"
    container_default_behavior: "no_defaults"
    state: started