---
- name: Create Calibre-Web container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_calibreweb_name }}"
    image: "{{ docker_calibreweb_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_calibreweb_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_calibreweb_name }}"
      fluentd-async: "true"
    env:
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
      TZ: "{{ homelab_timezone }}"
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
      PASSWORD: "{{ docker_calibreweb_admin_password }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.calibreweb.entrypoints: "websecure"
      traefik.http.routers.calibreweb.rule: "Host(`{{ docker_calibreweb_proxy_hostname }}`)"
      traefik.http.routers.calibreweb.tls: "true"
      traefik.http.routers.calibreweb.tls.certresolver: "le"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ docker_calibreweb_mount_config }}:/config"
      - "{{ docker_calibreweb_mount_media }}:/books"
    restart_policy: unless-stopped
    state: present

- name: Start Calibre-Web container
  docker_container:
    name: "{{ docker_calibreweb_name }}"
    container_default_behavior: "no_defaults"
    state: started