---
- name: Create Calibre-Web config directory
  file:
    path: "{{ docker_calibreweb_mount_config }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0755
    recurse: yes

- name: Determine if Calibre-Web media directory exists
  stat:
    path: "{{ docker_calibreweb_mount_media }}"
  register: media_path

- name: Create Calibre-Web media directory but don't mess with existing/mounted folder
  file:
    path: "{{ docker_calibreweb_mount_media }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0775
    state: directory
    recurse: yes
  when: not media_path.stat.exists