---
# -------------------------------------------------------------------------------------------------
# General rule for all servers
# Allow but limit SSH, block all other incoming traffic
# -------------------------------------------------------------------------------------------------

- hosts: grp_baremetal:grp_vm:grp_lxc:grp_cloud_vps
  tasks:
    - name: Reset FW rules
      ufw: 
        state: reset
    - name: Allow SSH
      ufw:
        rule: limit
        port: "22"
        proto: tcp
    - name: Set firewall default policy
      ufw: 
        state: enabled
        policy: reject
        log: yes

# -------------------------------------------------------------------------------------------------
# Host specific rules - Edge
# VPS server in Amazon Lightsail - VPN server (WireGuard), TCP balancer/proxy (HAproxy)
# -------------------------------------------------------------------------------------------------

- hosts: edge.blazcata.cz
  tasks:
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp
    - name: Allow Plex
      ufw:
        rule: allow
        port: "32400"
        proto: tcp
    - name: Allow Wireguard
      ufw:
        rule: allow
        port: "51194"
        proto: udp

# -------------------------------------------------------------------------------------------------
# Host specific rules - VLAN 90 (DMZ)
# RPi in DMZ - VPN client (WireGuard), TCP balancer/proxy (HAproxy)
# -------------------------------------------------------------------------------------------------

- hosts: dmz.blazcata.cz
  tasks:
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp
    - name: Allow Fluent Bit forward data
      ufw:
        rule: allow
        port: "24224"
        proto: tcp
    - name: Allow Plex
      ufw:
        rule: allow
        port: "32400"
        proto: tcp

# -------------------------------------------------------------------------------------------------
# Host specific rules - VLAN 30 (LAN)
# -------------------------------------------------------------------------------------------------

- hosts: data.blazcata.cz
  tasks:
    - name: Allow Samba
      ufw:
        rule: allow
        port: "445"
        proto: tcp

- hosts: spock.blazcata.cz
  tasks:
    - name: Allow Plex
      ufw:
        rule: allow
        port: "32400"
        proto: tcp

- hosts: kirk.blazcata.cz
  tasks:
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp
    - name: Allow Syslog UDP
      ufw:
        rule: allow
        port: "514"
        proto: udp
    - name: Allow Syslog TCP
      ufw:
        rule: allow
        port: "6514"
        proto: tcp

- hosts: picard.blazcata.cz
  tasks:
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp
    - name: Allow OpenHAB2/3
      ufw:
        rule: allow
        port: "8080,8081"
        proto: tcp
    - name: Allow Transmission UI
      ufw:
        rule: allow
        port: "9091"
        proto: tcp
    - name: Allow HomeKit <-> OpenHAB communication 
      ufw:
        rule: allow
        port: "9124"
        proto: tcp