---
# -------------------------------------------------------------------------------------------------
# Groups
# -------------------------------------------------------------------------------------------------

- hosts: grp_proxmox
  roles:
    - role: postfix_relay
      tags: [ postfix_relay ]

- hosts: grp_baremetal:grp_vm:grp_lxc:grp_cloud_vps
  roles:
    - role: logging
      tags: [ logging ]

- hosts: grp_samba
  roles:
    - role: samba
      tags: [ samba ]

- hosts: grp_haproxy
  roles:
    - role: haproxy
      tags: [ haproxy ]

- hosts: grp_docker
  roles:
    - role: docker
      tags: [ docker ]

- hosts: grp_traefik
  roles:
    - role: docker_traefik
      tags: [ traefik ]
    - role: docker_whoami
      tags: [ traefik ]

# -------------------------------------------------------------------------------------------------
# Proxmox1 (Mac Mini)
# -------------------------------------------------------------------------------------------------

# - hosts: proxmox1.blazcata.cz
#   roles:
#     - role: nut_slave
#       tags: [ nut_slave ]

# -------------------------------------------------------------------------------------------------
# Proxmox1 (Mac Mini) - Docker Internal
# -------------------------------------------------------------------------------------------------

- hosts: kirk.blazcata.cz
  roles:
    - role: samba_client
      tags: [ samba_client ]
    - role: docker_download
      tags: [ download ]

# -------------------------------------------------------------------------------------------------
# Proxmox1 (Mac Mini) - Docker DMZ
# -------------------------------------------------------------------------------------------------

- hosts: sisko.blazcata.cz
  roles:

# -------------------------------------------------------------------------------------------------
# Proxmox2 (NAS)
# -------------------------------------------------------------------------------------------------

- hosts: proxmox2.blazcata.cz
  roles:
    - role: nut_master
      tags: [ nut_master ]

# -------------------------------------------------------------------------------------------------
# Proxmox2 (NAS) - Docker Internal
# -------------------------------------------------------------------------------------------------

- hosts: picard.blazcata.cz
  roles:
    - role: samba_client
      tags: [ samba_client ]
    - role: docker_homer
      tags: [ homer ]
    - role: docker_openhab2
      tags: [ openhab2 ]
    - role: docker_authentik
      tags: [ authentik ]
    - role: docker_influxdb2
      tags: [ influxdb2, soc ]
    - role: docker_loki
      tags: [ loki, soc ]
    - role: docker_grafana
      tags: [ grafana, soc ]
    - role: docker_calibre-web
      tags: [ calibre-web ]
    - role: docker_photoprism
      tags: [ photoprism ]

# -------------------------------------------------------------------------------------------------
# Proxmox2 (NAS) - LXC Internal - Plex server
# -------------------------------------------------------------------------------------------------

- hosts: spock.blazcata.cz
  roles:
    - role: samba_client
      tags: [ samba_client ]
    - role: acmesh
      tags: [ acmesh ]
    - role: plex
      tags: [ plex ]