---
- name: Create GeoIP update container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_authentik_geoipupdate_name }}"
    image: "{{ docker_authentik_geoipupdate_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_authentik_geoipupdate_name }}"
      fluentd-async: "true"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    env:
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: "8"
    volumes:
      - "{{ docker_authentik_mount_geoip }}:/usr/share/GeoIP"
    user: "{{ docker_uid }}:{{ docker_gid }}"
    restart_policy: unless-stopped
    state: present

- name: Start GeoIP update container
  docker_container:
    name: "{{ docker_authentik_geoipupdate_name }}"
    container_default_behavior: "no_defaults"
    state: started