---
- name: Create Redis container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_authentik_redis_name }}"
    image: "{{ docker_authentik_redis_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_authentik_redis_name }}"
      fluentd-async: "true"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ docker_authentik_mount_redis }}:/data"
    restart_policy: unless-stopped
    state: present

- name: Start Redis container
  docker_container:
    name: "{{ docker_authentik_redis_name }}"
    container_default_behavior: "no_defaults"
    state: started