---
- name: Create PostgreSQL container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_authentik_postgresql_name }}"
    image: "{{ docker_authentik_postgresql_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_authentik_postgresql_name }}"
      fluentd-async: "true"
    env:
      POSTGRES_USER: "{{ docker_authentik_postgresql_user }}"
      POSTGRES_PASSWORD: "{{ docker_authentik_postgresql_password }}"
      POSTGRES_DB: "{{ docker_authentik_postgresql_db }}"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ docker_authentik_mount_postgresql }}:/var/lib/postgresql/data"
    user: "{{ docker_uid }}:{{ docker_gid }}"
    restart_policy: unless-stopped
    state: present

- name: Start PostgreSQL container
  docker_container:
    name: "{{ docker_authentik_postgresql_name }}"
    container_default_behavior: "no_defaults"
    state: started