---
- name: Adding Plex key - Ubuntu
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Adding Plex repository
  apt_repository:
    repo: "deb https://downloads.plex.tv/repo/deb public main"
    state: present

- name: Installing packages
  apt:
    pkg:
      - cifs-utils
      - plexmediaserver
      - i965-va-driver
      - vainfo
    state: latest
    update_cache: yes

- name: Adding user
  user:
    append: yes
    name: "plex"
    home: "/var/lib/plexmediaserver"
    shell: "/usr/sbin/nologin"
    groups: "video,render"
    system: yes
    state: present

- name: Restarting Plex Media Server
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: plexmediaserver