---
homelab_timezone: "Europe/Prague"
homelab_user: "homelab"
homelab_user_home: "/home/{{ homelab_user }}"
homelab_user_uid: "1000"
homelab_group: "homelab"
homelab_group_gid: "1000"

acme_email: "nobody@acme.com"
acme_domain: "acme.com"
# CloudFlare DNS API
acme_dns_cf_email: "nobody@acme.com"
acme_dns_cf_account: "change me!"
acme_dns_cf_token: "change me!"

docker_user: "{{ homelab_user }}"
docker_uid: "{{ homelab_user_uid }}"
docker_group: "{{ homelab_group }}"
docker_gid: "{{ homelab_group_gid }}"
docker_network: homelab_net
docker_data_basepath: "/opt/homelab/docker"