---
samba_configuration_dir: /etc/samba
samba_configuration: "{{ samba_configuration_dir }}/smb.conf"
samba_username_map_file: "{{ samba_configuration_dir }}/smbusers"

samba_services:
  - smbd
  - nmbd

samba_log: /var/log/samba/samba.log
samba_log_size: 5000
samba_log_level: "1 auth_audit:3"

samba_workgroup: 'WORKGROUP'
samba_server_string: "{{ inventory_hostname }}"

samba_shares_root: '/mnt/nas/shares'
samba_shares: []
samba_users: []