---
- name: Creating Homer container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_homer_name }}"
    image: "{{ docker_homer_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_homer_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_homer_name }}"
      fluentd-async: "true"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ docker_homer_mount_config }}:/www/assets"
    env:
      UID: "{{ docker_user_uid }}"
      GID: "{{ docker_group_gid }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homer.entrypoints: "websecure"
      traefik.http.routers.homer.rule: "Host(`{{ docker_homer_proxy_hostname }}`)"
      traefik.http.routers.homer.tls: "true"
      traefik.http.routers.homer.tls.certresolver: "le"
    restart_policy: unless-stopped
    state: present

- name: Starting Homer container
  docker_container:
    name: "{{ docker_homer_name }}"
    container_default_behavior: "no_defaults"
    state: started