- name: Check if firewall rules have changed
  template:
    src: "rules.j2"
    dest: "/tmp/ansible.ufw.rules"
    mode: 0600
  register: ufw_existing_rules

- name: Reset firewall rules
  ufw:
    state: reset
  when: ufw_existing_rules.changed

- name: "Set default incoming policy to {{ ufw_default_incoming_policy }}"
  ufw:
    policy: "{{ ufw_default_incoming_policy }}"
    direction: incoming
  when: ufw_existing_rules.changed

- name: "Set default outgoing policy to {{ ufw_default_outgoing_policy }}"
  ufw:
    policy: "{{ ufw_default_outgoing_policy }}"
    direction: outgoing
  when: ufw_existing_rules.changed

- name: Apply default rules
  ufw:
    comment: "{{ item.comment | default(omit) }}"
    default: "{{ item.default | default(omit) }}"
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    insert_relative_to: "{{ item.insert_relative_to | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    interface_in: "{{ item.interface_in | default(omit) }}"
    interface_out: "{{ item.interface_out | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    route: "{{ item.route | default(omit) }}"
    rule: "{{ item.rule | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: "{{ ufw_default_rules }}"
  when: ufw_default_rules|default('')|length > 0 and ufw_existing_rules.changed

- name: Apply custom rules
  ufw:
    comment: "{{ item.comment | default(omit) }}"
    default: "{{ item.default | default(omit) }}"
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    insert_relative_to: "{{ item.insert_relative_to | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    interface_in: "{{ item.interface_in | default(omit) }}"
    interface_out: "{{ item.interface_out | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    route: "{{ item.route | default(omit) }}"
    rule: "{{ item.rule | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: "{{ ufw_custom_rules }}"
  when: ufw_custom_rules|default('')|length > 0 and ufw_existing_rules.changed

- name: "Ensure firewall is {{ ufw_state }}"
  ufw:
    state: "{{ ufw_state }}"