---
- name: Download borgbackup
  get_url:
    url: "https://github.com/borgbackup/borg/releases/download/{{ borg_pkg_version }}/borg-{{ borg_os_variant }}"
    dest: /usr/local/bin/borg
    mode: 0755