---
- name: Creating Navidrome data directory
  file:
    path: "{{ docker_navidrome_mount_data }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0755
    recurse: yes

- name: Determine if music directory exists
  stat:
    path: "{{ docker_navidrome_mount_music }}"
  register: media_path

- name: Create music directory but don't mess with existing/mounted folder
  file:
    path: "{{ docker_navidrome_mount_music }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0775
    state: directory
    recurse: yes
  when: not media_path.stat.exists

- name: Create Navidrome container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_navidrome_name }}"
    image: "{{ docker_navidrome_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "{{ docker_navidrome_memory }}"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_navidrome_name }}"
      fluentd-async: "true"
    env:
      ND_SCANSCHEDULE: "15m"
      ND_ENABLETRANSCODINGCONFIG: 'false'
    labels:
      traefik.enable: "true"
      traefik.http.routers.navidrome.entrypoints: "websecure"
      traefik.http.routers.navidrome.rule: "Host(`{{ docker_navidrome_proxy_hostname }}`)"
      traefik.http.routers.navidrome.tls: "true"
      traefik.http.routers.navidrome.tls.certresolver: "le"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ docker_navidrome_mount_data }}:/data"
      - "{{ docker_navidrome_mount_music }}:/music:ro"
    user: "{{ docker_uid }}:{{ docker_gid }}"
    restart_policy: unless-stopped
    state: present

- name: Start Navidrome container
  docker_container:
    name: "{{ docker_navidrome_name }}"
    container_default_behavior: "no_defaults"
    state: started