---
docker_traefik_name: traefik
docker_traefik_image: 'traefik:v2.5'

docker_traefik_basepath: "{{ docker_data_basepath }}/traefik"
docker_traefik_mount_traefik_yml: "{{ docker_traefik_basepath }}/traefik.yml"
docker_traefik_mount_acme_json: "{{ docker_traefik_basepath }}/acme.json"

docker_traefik_proxy_hostname: "{{ inventory_hostname }}"

docker_traefik_admin: "traefik"
docker_traefik_password: "changeme!"