- name: Constructing kernel version entry
  command: uname -r
  register: kernel_version

- name: Installing packages
  apt:
    pkg:
      - cifs-utils
      - "linux-modules-extra-{{ kernel_version.stdout }}"
    state: present
    update_cache: yes

- name: Create local mounts
  file:
    state: directory
    path: "{{ item.local_mount }}"
    owner: "{{ homelab_user }}"
    group: "{{ homelab_group }}"
    mode: 0775
    recurse: yes
  with_items: "{{ samba_client_shares }}"

- name: Ensure the credentials file exists for each mount
  template:
    src: "smb.j2"
    dest: "/root/.smb_{{ item.name }}"
    mode: 0600
  with_items: '{{ samba_client_shares }}'

- name: Mounting CIFS share
  mount:
    src: "{{ item.samba_share }}"
    path: "{{ item.local_mount }}"
    fstype: cifs
    opts: "credentials=/root/.smb_{{ item.name }},iocharset=utf8,vers=3.0,nofail,uid={{ homelab_user_uid }},gid={{ homelab_user_gid }}"
    state: mounted
  with_items: "{{ samba_client_shares }}"