---
- name: Create items folder
  file:
    path: "{{ docker_openhab3_mount_conf }}/items"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
  become: yes

- name: Copy items files
  template:
    src: "{{ item }}"
    dest: "{{ docker_openhab3_mount_conf }}/items/{{ item | basename }}"
    mode: '644'
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
  with_fileglob:
    - ../templates/items/*.items