---
- name: Create things folder
  file:
    path: "{{ docker_openhab3_mount_conf }}/things"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
  become: yes

- name: Copy things files
  template:
    src: "{{ item }}"
    dest: "{{ docker_openhab3_mount_conf }}/things/{{ item | basename }}"
    mode: '644'
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
  with_fileglob:
    - ../templates/things/*.things