---
- name: Create openHAB3 container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_openhab3_name }}"
    image: "{{ docker_openhab3_image }}"
    #pull: yes
    recreate: yes
    env:
      USER_ID: "{{ docker_uid }}"
      GROUP_ID: "{{ docker_gid }}"
      CRYPTO_POLICY: "unlimited"
      #OPENHAB_HTTP_ADDRESS: '127.0.0.1'
      OPENHAB_HTTP_PORT: "docker_openhab3_http_port"
      OPENHAB_HTTPS_PORT: "docker_openhab3_https_port"
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ docker_openhab3_mount_conf }}:/openhab/conf"
      - "{{ docker_openhab3_mount_userdata }}:/openhab/userdata"
      - "{{ docker_openhab3_mount_addons }}:/openhab/addons"
    restart_policy: unless-stopped
    state: present

- name: Start openHAB3
  docker_container:
    name: "{{ docker_openhab3_name }}"
    state: started