# -------------------------------------------------------------------------------------------------
# Groups
# -------------------------------------------------------------------------------------------------

- hosts: grp_proxmox
  roles:
    - role: postfix_relay
      tags: [ postfix_relay ]
    - role: borgbackup
      tags: [ borgbackup ]

# -------------------------------------------------------------------------------------------------
# Proxmox1 (Mac Mini)
# -------------------------------------------------------------------------------------------------

# - hosts: proxmox1.blazcata.cz
#   roles:
#     - role: nut_slave
#       tags: [ nut_slave ]

# -------------------------------------------------------------------------------------------------
# Proxmox2 (NAS)
# -------------------------------------------------------------------------------------------------

- hosts: proxmox2.blazcata.cz
  roles:
    - role: nut_master
      tags: [ nut_master ]
