---
- name: Create local mounts
  file:
    state: directory
    path: "{{ item.local_mount }}"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0775
    recurse: yes
  with_items: "{{ samba_client_shares }}"

- name: Ensure the credentials file exists for each mount
  template:
    src: "smb.j2"
    dest: "/root/.smb_{{ item.name }}"
    mode: 0600
  with_items: '{{ samba_client_shares }}'

- name: Mounting CIFS share
  mount:
    src: "{{ item.samba_share }}"
    path: "{{ item.local_mount }}"
    fstype: cifs
    opts: "credentials=/root/.smb_{{ item.name }},iocharset=utf8,vers=3.0,nofail,uid={{ item.custom_local_uid | default(samba_client_default_local_uid) }},gid={{ item.custom_local_gid | default(samba_client_default_local_gid) }}"
    state: mounted
  with_items: "{{ samba_client_shares }}"