---
- name: Constructing kernel version entry
  command: uname -r
  register: kernel_version

- name: Installing cifs-utils
  apt:
    pkg:
      - cifs-utils
    state: present
    update_cache: yes
    cache_valid_time: "{{ system_apt_cache_valid_time }}"

- name: Installing kernel modules extra
  apt:
    pkg:
      - "linux-modules-extra-{{ kernel_version.stdout }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ system_apt_cache_valid_time }}"
  when: "'grp_vm' in group_names"