---
- name: Create Loki container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_loki_name }}"
    image: "{{ docker_loki_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_loki_name }}"
      fluentd-async: "true"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    networks_cli_compatible: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.loki.entrypoints: "websecure"
      traefik.http.routers.loki.rule: "Host(`{{ docker_loki_proxy_hostname }}`)"
      traefik.http.routers.loki.tls: "true"
      traefik.http.routers.loki.tls.certresolver: "le"
      traefik.http.routers.loki.middlewares: "loki-auth"
      traefik.http.middlewares.loki-auth.basicauth.users: "{{ docker_loki_admin }}:{{ docker_loki_password | password_hash('blowfish') }}"
    volumes:
      - "{{ docker_loki_mount_data }}:/data/loki"
      - "{{ docker_loki_mount_config }}:/etc/loki"
    user: "{{ docker_uid }}"
    restart_policy: unless-stopped
    state: present

- name: Start Loki
  docker_container:
    name: "{{ docker_loki_name }}"
    container_default_behavior: "no_defaults"
    state: started