---
- name: Creating whoami container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "whoami"
    image: "traefik/whoami"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    memory: "64m"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.whoami"
      fluentd-async: "true"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.entrypoints: "websecure"
      traefik.http.routers.whoami.rule: "Host(`{{ docker_traefik_proxy_hostname }}`) && PathPrefix(`/who`)"
      traefik.http.routers.whoami.tls: "true"
      traefik.http.routers.whoami.tls.certresolver: "le"
    restart_policy: unless-stopped
    state: present

- name: Starting whoami container
  docker_container:
    name: "whoami"
    container_default_behavior: "no_defaults"
    state: started