---
- name: Remove Exim
  apt:
    pkg:
      - exim4-base
      - exim4-config
      - exim4-daemon-light
    state: absent
    purge: yes

- name: Install Postfix
  apt:
    pkg:
      - postfix
      - libsasl2-modules
    update_cache: yes
    cache_valid_time: "{{ system_apt_cache_valid_time }}"
    state: present