---
- name: Create InfluxDB 2 container
  docker_container:
    docker_host: unix://var/run/docker.sock
    detach: yes
    name: "{{ docker_influxdb2_name }}"
    image: "{{ docker_influxdb2_image }}"
    pull: yes
    recreate: yes
    container_default_behavior: "no_defaults"
    log_driver: fluentd
    log_options:
      tag: "log.local.docker.{{ docker_influxdb2_name }}"
      fluentd-async: "true"
    env:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "{{ docker_influxdb2_admin }}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "{{ docker_influxdb2_password }}"
      DOCKER_INFLUXDB_INIT_ORG: "{{ docker_influxdb2_org }}"
      DOCKER_INFLUXDB_INIT_BUCKET: "{{ docker_influxdb2_bucket }}"
      DOCKER_INFLUXDB_INIT_RETENTION: "{{ docker_influxdb2_retention }}"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ docker_influxdb2_admin_token }}"
    network_mode: bridge
    networks:
      - name: "{{ docker_network }}"
    networks_cli_compatible: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.influxdb2.entrypoints: "websecure"
      traefik.http.routers.influxdb2.rule: "Host(`{{ docker_influxdb2_proxy_hostname }}`)"
      traefik.http.routers.influxdb2.tls: "true"
      traefik.http.routers.influxdb2.tls.certresolver: "le"
    volumes:
      - "{{ docker_influxdb2_mount_data }}:/var/lib/influxdb2"
      - "{{ docker_influxdb2_mount_config }}:/etc/influxdb2"
    user: "{{ docker_uid }}"
    restart_policy: unless-stopped
    state: present

- name: Start InfluxDB 2
  docker_container:
    name: "{{ docker_influxdb2_name }}"
    container_default_behavior: "no_defaults"
    state: started