---
- name: Creating Traefik directory
  file:
    path: "{{ docker_traefik_basepath }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0755
    recurse: yes

- name: Copying traefik.yml
  template:
    src: "traefik.yml.j2"
    dest: "{{ docker_traefik_mount_traefik_yml }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0600

- name: Creating acme.json
  file:
    path: "{{ docker_traefik_mount_acme_json }}"
    state: touch
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0600